#!/usr/bin/env node
// Regenerates every page that was rebuilt onto the homepage design, plus the
// sitemap. There is no bundler in this project — the generated HTML is
// committed alongside the generator, and this script is the only way those
// files should be edited so prices and disclosure language cannot drift.
//
//   node tools/build-pages.mjs            write the files
//   node tools/build-pages.mjs --check    fail if any file is out of date

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import {
  repoRoot,
  business,
  pricing,
  jsonLd,
  localBusiness,
  faqSchema,
  stripTags,
} from "./lib/site.mjs";
import {
  carpetPage,
  ductPage,
  upholsteryPage,
  luxuryPage,
} from "./pages/services.mjs";
import { aboutPage, contactPage, reviewsPage } from "./pages/company.mjs";
import { areaPages } from "./pages/areas.mjs";

const check = process.argv.includes("--check");

// ---------------------------------------------------------------------------
// The homepage is hand-authored — it is the design every other page was
// rebuilt to match, and it is not worth turning into a template. Its
// structured data is generated, though, so the prices inside it come from the
// catalog like everywhere else. The block between the two markers below is
// replaced on every run.
// ---------------------------------------------------------------------------

const SCHEMA_START =
  "  <!-- schema:start — generated by tools/build-pages.mjs; do not edit by hand -->";
const SCHEMA_END = "  <!-- schema:end -->";

function homepageSchema(html) {
  // The FAQ accordion is the source of truth for the FAQPage node: the visible
  // answer and the marked-up answer are the same string by construction.
  const faqBlock = html.slice(
    html.indexOf('<div class="faq-list">'),
    html.indexOf("</div>", html.indexOf('<div class="faq-list">')),
  );
  const faqs = [
    ...faqBlock.matchAll(
      /<details><summary>([\s\S]*?)<\/summary>([\s\S]*?)<\/details>/g,
    ),
  ].map(([, q, a]) => [stripTags(q), stripTags(a)]);
  if (faqs.length < 4) {
    throw new Error(
      `index.html FAQ extraction found only ${faqs.length} entries`,
    );
  }
  return [
    localBusiness({ url: `${business.origin}/` }),
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "@id": `${business.origin}/#website`,
      url: `${business.origin}/`,
      name: business.name,
      publisher: { "@id": `${business.origin}/#business` },
      inLanguage: "en-US",
    },
    faqSchema(faqs),
  ];
}

function patchHomepage() {
  const target = resolve(repoRoot, "index.html");
  let html = readFileSync(target, "utf8");
  const block = `${SCHEMA_START}\n${jsonLd(
    ...homepageSchema(html),
  )}\n${SCHEMA_END}`;
  const start = html.indexOf(SCHEMA_START);
  if (start === -1) {
    // A function replacer, not a string: `$$` inside the JSON-LD (priceRange)
    // would otherwise be collapsed to a single `$` by replacement-pattern
    // substitution.
    html = html.replace("</head>", () => `${block}\n</head>`);
  } else {
    const end = html.indexOf(SCHEMA_END, start) + SCHEMA_END.length;
    html = html.slice(0, start) + block + html.slice(end);
  }
  return html;
}

const outputs = [
  ["index.html", patchHomepage()],
  ["carpet-cleaning.html", carpetPage()],
  ["air-duct-cleaning.html", ductPage()],
  ["upholstery-cleaning.html", upholsteryPage()],
  ["luxury-designer-furniture-cleaning.html", luxuryPage()],
  ["about.html", aboutPage()],
  ["contact.html", contactPage()],
  ["reviews.html", reviewsPage()],
  ...areaPages().map((p) => [p.file, p.html]),
];

// ---------------------------------------------------------------------------
// Sitemap
// ---------------------------------------------------------------------------

// Every canonical URL, in the order a reader would meet them. Retired and
// duplicate paths (/privacy-policy, /terms, /promotion, bare .html twins) are
// deliberately absent: they are 301s in _redirects, not indexable pages.
const SITEMAP = [
  ["/", "1.0", "weekly"],
  ["/book", "0.9", "weekly"],
  ["/book/carpet", "0.6", "monthly"],
  ["/book/air-ducts", "0.6", "monthly"],
  ["/book/upholstery", "0.6", "monthly"],
  ["/book/move", "0.6", "monthly"],
  ["/book/add-ons", "0.5", "monthly"],
  ["/book/review", "0.5", "monthly"],
  ["/carpet-cleaning", "0.9", "monthly"],
  ["/air-duct-cleaning", "0.9", "monthly"],
  ["/upholstery-cleaning", "0.9", "monthly"],
  ["/luxury-designer-furniture-cleaning", "0.7", "monthly"],
  ["/move-in-move-out-cleaning", "0.8", "monthly"],
  ["/promotions", "0.8", "weekly"],
  ["/about", "0.7", "monthly"],
  ["/contact", "0.8", "monthly"],
  ["/reviews", "0.6", "monthly"],
  ["/service-terms", "0.4", "yearly"],
  ["/privacy", "0.3", "yearly"],
  ["/return-refund-policy", "0.3", "yearly"],
  ...areaPages().map((p) => [p.path, "0.7", "monthly"]),
];

// The catalog stamps its own revision date; using it keeps <lastmod> honest
// instead of moving every URL to today on every run.
const lastmod = pricing.version;

const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${SITEMAP.map(
  ([path, priority, freq]) => `  <url>
    <loc>${business.origin}${path}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${freq}</changefreq>
    <priority>${priority}</priority>
  </url>`,
).join("\n")}
</urlset>
`;

outputs.push(["sitemap.xml", sitemapXml]);

// ---------------------------------------------------------------------------

let stale = 0;
let written = 0;
for (const [file, contents] of outputs) {
  const target = resolve(repoRoot, file);
  const current = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (current === contents) continue;
  if (check) {
    stale++;
    console.error(`stale: ${file}`);
    continue;
  }
  writeFileSync(target, contents);
  written++;
  console.log(`wrote ${file}`);
}

if (check) {
  if (stale) {
    console.error(
      `\n${stale} file(s) out of date. Run: node tools/build-pages.mjs`,
    );
    process.exit(1);
  }
  console.log(`${outputs.length} generated file(s) up to date.`);
} else {
  console.log(
    `\n${written} written, ${outputs.length - written} already current.`,
  );
}
